# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# FIXME this is an experiment

# Articles all languages
GET http://backend.emanuelesantanche.com/rest/EMS/view/articlesplayground?_format=json

###

# Articles filtered on language
GET http://backend.emanuelesantanche.com/rest/EMS/view/articles?_format=json&langcode=en

###

# &field_ems_topic_target_id="How I work"&sticky=1 (with sticky=1 I get only the sticky ones)
GET http://backend.emanuelesantanche.com/rest/EMS/view/articles?_format=hal_json&field_ems_topic_target_id="How I work"

###

# &nid=4 single article and language
GET http://backend.emanuelesantanche.com/rest/EMS/view/articles?_format=json&nid=58&langcode=en

###


# test of view with json api
GET http://backend.emanuelesantanche.com/rest/EMS/view/articlesplayground?_format=json

###

#
GET https://backend.emanuelesantanche.com/rest/EMS/view/articlesplayground?_format=json&langcode=en&field_ems_topic_target_id="Talking about my experiences"&page=0

###

# test json api
# fields[node--ems_article]=title,body,sticky,field_ems_topic
# filter[field_name]=value
# &include=field_ems_topic
#GET http://backend.emanuelesantanche.com/jsonapi/node/ems_article?fields[node--ems_article]=title,body,sticky,field_ems_topic,field_image&include=field_ems_topic&page[limit]=6&page[offset]=0

###